# **Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes**

-------------

The multinomial Naive Bayes classifier is suitable for classification with discrete features (e.g., word counts for text classification). The multinomial distribution normally requires integer feature counts. However, in practice, fractional counts such as tf-idf may also work.

## **Import Library**

In [174]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

## **Import Data**

In [175]:
data = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

## **Describe Data**

In [176]:
data.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [177]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [178]:
data.shape

(23486, 10)

## **Data Preprocessing**

In [179]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [180]:
data[data['Review']==""]=np.NaN

In [181]:
data['Review'].fillna("No Review",inplace=True)

In [182]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [183]:
data['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [184]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

## **Define Target Variable (y) and Feature Variables (X)**

In [185]:
data.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [186]:
x = data['Review']
x

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [187]:
y = data['Rating']
y

0        4.0
1        5.0
2        3.0
3        5.0
4        5.0
        ... 
23481    5.0
23482    3.0
23483    3.0
23484    3.0
23485    5.0
Name: Rating, Length: 23486, dtype: float64

In [188]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

## **Train Test Split**

In [189]:
from sklearn.model_selection import train_test_split

In [190]:
X_train,X_test,y_train,y_test= train_test_split(x,y,test_size=0.3,stratify=y,random_state=4356)

In [191]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape,

((16440,), (7046,), (16440,), (7046,))

In [192]:
from sklearn.feature_extraction.text import CountVectorizer

In [193]:
cv = CountVectorizer(lowercase=True,analyzer="word",ngram_range=(2,3),stop_words="english",max_features=5000)

In [194]:
X_train = cv.fit_transform(X_train)

In [195]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'yellow color',
       'yesterday store', 'yoga pants'], dtype=object)

In [196]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [197]:
X_test = cv.fit_transform(X_test)

In [198]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yellow color'], dtype=object)

In [199]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## **Modeling**

In [200]:
from sklearn.naive_bayes import MultinomialNB

In [201]:
model = MultinomialNB()

In [202]:
model.fit(X_train,y_train)

MultinomialNB()

## **Prediction**

In [203]:
y_pred = model.predict(X_test)

In [204]:
y_pred.shape

(7046,)

In [205]:
y_pred

array([5., 5., 4., ..., 5., 4., 4.])

In [206]:
model.predict_proba(X_test)

array([[0.00127592, 0.00218213, 0.01298631, 0.12064841, 0.86290723],
       [0.00621143, 0.00483381, 0.00124817, 0.29015424, 0.69755234],
       [0.29213979, 0.04036731, 0.14538751, 0.45136149, 0.0707439 ],
       ...,
       [0.02470182, 0.05428784, 0.05638531, 0.0121026 , 0.85252243],
       [0.05467865, 0.05106192, 0.07325014, 0.55249666, 0.26851263],
       [0.27600548, 0.03316413, 0.01119467, 0.41685247, 0.26278325]])

## **Model Evaluation**

In [207]:
from sklearn.metrics import confusion_matrix,classification_report

In [208]:
print(confusion_matrix(y_test,y_pred))

[[  22   27   27   39  138]
 [  51   51   68  102  198]
 [ 105   88  140  174  354]
 [ 147   96  158  374  748]
 [ 352  214  292  647 2434]]


In [209]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.03      0.09      0.05       253
         2.0       0.11      0.11      0.11       470
         3.0       0.20      0.16      0.18       861
         4.0       0.28      0.25      0.26      1523
         5.0       0.63      0.62      0.62      3939

    accuracy                           0.43      7046
   macro avg       0.25      0.24      0.24      7046
weighted avg       0.45      0.43      0.44      7046



# Recatagories Rating as Poor(0) and Good(1)

In [210]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [211]:
data.replace({'Rating' : { 1 : 0, 2 : 0, 3 : 0, 4 : 1, 5 : 1}}, inplace = True)
# data['Rating'].value_counts()

In [212]:
x = data['Review']

In [213]:
y = data['Rating']

## Train Test Split

In [214]:
from sklearn.model_selection import train_test_split

In [215]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state=2529)

In [216]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# Get Features Text Conversion to Tokens

In [217]:
from sklearn.feature_extraction.text import CountVectorizer

In [218]:
cv = CountVectorizer(lowercase=True,ngram_range=(2,3),analyzer="word",stop_words="english",max_features=5000)

In [219]:
X_train = cv.fit_transform(X_train)

In [220]:
X_test = cv.fit_transform(X_test)

# Get Model Re Train

In [221]:
from sklearn.naive_bayes import MultinomialNB

In [222]:
model = MultinomialNB()

In [223]:
model.fit(X_train,y_train)

MultinomialNB()

In [224]:
y_pred = model.predict(X_test)

In [225]:
y_pred.shape

(7046,)

In [226]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

In [227]:
from sklearn.metrics import confusion_matrix,classification_report

In [229]:
print(confusion_matrix(y_test,y_pred))

[[ 449 1134]
 [ 989 4474]]


In [230]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.31      0.28      0.30      1583
         1.0       0.80      0.82      0.81      5463

    accuracy                           0.70      7046
   macro avg       0.56      0.55      0.55      7046
weighted avg       0.69      0.70      0.69      7046



## **Explaination**

We can say that from 5 degree of Rating results in less accuracy, Whereas with 2 degree of Rating results with incresed accuracy.